/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComCouponList: typeof import('./src/components/ComCouponList.vue')['default']
    GetPhoneNumber: typeof import('./src/components/getPhoneNumber.vue')['default']
    GetUserInfo: typeof import('./src/components/getUserInfo.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCountdown: typeof import('@nutui/nutui-taro')['Countdown']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutSkeleton: typeof import('@nutui/nutui-taro')['Skeleton']
    NutSwitch: typeof import('@nutui/nutui-taro')['Switch']
  }
}
